[package]
name = "rtmpserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
serde_json = "1.0"
serde = "1.0"
tokio = { version = "1", features = ["full"] }
rtmp = "0.3.1"
anyhow = "1.0.40"
log = "0.4.14"
gstreamer = "0.20.7"
gstreamer-video = "0.20.7"
gstreamer-app = "0.20.7"
http = "0.2"
libc = "0.2"
hyper = { version = "0.14.27", features = ["full"] }
